Makefile should put -lpthread in LDLIBS instead of LDFLAG
Linux skylake 4.2.0-25-generic
gcc version 5.3.0 20151204 (Ubuntu 5.3.0-3ubuntu1~14.04)
GNU Make 3.81

gcc -Wall -O2 -g -I../../include  -c -o inherit.o inherit.c
gcc -lpthread  inherit.o ../../lib/libhelper.a   -o inherit
inherit.o: In function `main':
/home/nate/git/perf_event_tests/tests/attr_fields/inherit.c:75: undefined reference to `pthread_create'
/home/nate/git/perf_event_tests/tests/attr_fields/inherit.c:79: undefined reference to `pthread_join'
/home/nate/git/perf_event_tests/tests/attr_fields/inherit.c:119: undefined reference to `pthread_create'
/home/nate/git/perf_event_tests/tests/attr_fields/inherit.c:123: undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make[2]: *** [inherit] Error 1
make[2]: Leaving directory `/home/nate/git/perf_event_tests/tests/attr_fields'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/nate/git/perf_event_tests/tests'
make: *** [all] Error 2

The problem is that only symbols that have already been seen are
grabbed from libpthread, and the default recipe for linking a single
object file puts LDFLAGS at the start of the command line:

‘$(CC) $(LDFLAGS) n.o $(LOADLIBES) $(LDLIBS)’
https://www.gnu.org/software/make/manual/html_node/Catalogue-of-Rules.html

Moving -lpthread to LDLIBS (or LOADLIBES) puts it at the end of the
command where it works.